package tests.employees;

import Base.DriverFactory;
import Base.UserModuleTest;
import Pages.ChangePasswordModal;
import Pages.UsersPage;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import utilities.ExecutionGuard;
import utilities.TestUser;

public class ChangeUserPasswordTest extends UserModuleTest {

    @BeforeMethod(alwaysRun = true)
    public void requirePasswordChangePermission() {
        ExecutionGuard.requireDestructiveTestsEnabled();
    }

    @Test
    public void changeUserPassword() {
        String user = System.getProperty("test.user.existing", "");
        if (user.isBlank()) {
            TestUser created = createActiveUser();
            user = created.name;
        }
        String password = System.getProperty("test.user.password", "Test@1234");
        UsersPage users = new UsersPage(DriverFactory.getDriver());
        ChangePasswordModal modal = new ChangePasswordModal(DriverFactory.getDriver());     

        users.search(user);
        users.openChangePassword(user);
        modal.setPassword(password, true);
        modal.update();

        Assert.assertTrue(modal.isClosed(),
                "Expected the change-password modal to close after a successful update.");
    }

    @Test
    public void changeUserPasswordAutoGenerated() {
        String user = System.getProperty("test.user.existing", "");
        if (user.isBlank()) {
            TestUser created = createActiveUser();
            user = created.name;
        }
        UsersPage users = new UsersPage(DriverFactory.getDriver());
        ChangePasswordModal modal = new ChangePasswordModal(DriverFactory.getDriver());

        users.search(user);
        users.openChangePassword(user);
        modal.clickAutoGeneratePassword();

        Assert.assertFalse(modal.getNewPasswordValue().isEmpty(),
                "Expected auto-generated password field to be populated.");

        modal.update();
        Assert.assertTrue(modal.isClosed(),
                "Expected change-password modal to close after auto-generating and updating.");
    }
}
